#!/usr/bin/env python3
"""
Scaffold a new skill under `skills/<name>/`.

Creates a minimal skill structure that's ready to fill in:
    skills/<name>/
    ├── SKILL.md              (with placeholder name + description)
    ├── README.md
    ├── CHANGELOG.md
    ├── build.config.json     (optional overrides for the build script)
    ├── references/
    │   └── example.md        (placeholder you'll rename/replace)
    └── evals/
        └── example.md        (placeholder test prompt)

Usage:
    python scripts/new_skill.py <skill-name> [--description "Short description"]
"""

from __future__ import annotations

import argparse
import sys
from datetime import date
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
SKILLS_DIR = ROOT / "skills"


SKILL_MD_TEMPLATE = """---
name: {name}
description: {description}
---

# {title}

Replace this opening paragraph with a one-sentence summary of what this skill does and when an AI assistant should consult it.

## CRITICAL: Detect the version / context FIRST

If this skill applies only to a specific version, framework, or environment, the assistant must verify that before applying any rules. Edit this section to fit your skill, or remove it if not applicable.

For example, for a framework-version-specific skill:
1. Read the relevant manifest/config file (e.g., `package.json`, `pyproject.toml`).
2. Confirm the framework and version.
3. If the version doesn't match, **STOP** and use the assistant's general knowledge instead of this skill.

## How to use this skill

The detailed rules are split by domain in `references/`. **Load only the references relevant to the current task.**

| Task involves... | Load this reference |
|---|---|
| (domain A) | `references/<topic-a>.md` |
| (domain B) | `references/<topic-b>.md` |

## Workflow for a code-generation request

1. Detect the version/context (per the section above). If it doesn't match, exit this skill.
2. Identify the task domain(s).
3. Load relevant references.
4. Generate code following the reference patterns.
5. **Self-check before responding** — scan your draft for the red flags below.

## Self-check checklist

Common red flags to fix before sending a response:

- (Red flag 1) → (correct pattern)
- (Red flag 2) → (correct pattern)
- ...
"""


README_TEMPLATE = """# {title}

> One-sentence description of what this skill does.

## What it covers

- Topic A — brief description
- Topic B — brief description

## Install

Pick your AI tool below. Each distribution is generated by `scripts/build.py` and lives under `dist/{name}/`.

### Claude (Anthropic)

Upload `dist/{name}/{name}.skill` in Claude.ai → Settings → Capabilities → Skills.

### Cursor

Copy `dist/{name}/cursor/.cursor/` to your project root.

### GitHub Copilot

Copy `dist/{name}/copilot/.github/copilot-instructions.md` to your project's `.github/`.

### Other tools

See `dist/{name}/<tool>/README.md` for Cline, Windsurf, Aider, Continue.dev, or the generic single-file markdown.

## Tested with

Test prompts live in `evals/`. Run them manually against the skill to validate behavior.

## Modify

Edit `SKILL.md` or any file under `references/`, then from the repo root:

```bash
python scripts/build.py --skill {name}
```

This regenerates `dist/{name}/` for every provider.
"""


CHANGELOG_TEMPLATE = """# Changelog — {name}

## [0.1.0] — {today}

Initial draft.
"""


BUILD_CONFIG_TEMPLATE = """{
  "_comment": "Optional skill-level overrides for the build script. Delete keys you don't need.",
  "reference_order": [],
  "reference_titles": {},
  "globs": {
    "_example": ["**/src/**/*.ts"]
  }
}
"""


EXAMPLE_REFERENCE = """# Example reference

This is a placeholder reference file. Rename it to match the domain it covers (e.g., `orm.md`, `routing.md`, `state-management.md`) and replace this content with concrete rules and code examples.

## A rule

```
example pattern
```

## Another rule

```
another example
```
"""


EXAMPLE_EVAL = """# Test Case 1: Example prompt

## User Prompt

(Write a representative user prompt that should trigger this skill.)

## What we're testing

- Specific behavior 1
- Specific behavior 2

## Expected output

(Sketch what the assistant should produce.)

## Anti-patterns to flag

- Common mistake 1
- Common mistake 2
"""


def write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    if path.exists():
        raise SystemExit(f"❌ File already exists: {path}")
    path.write_text(content, encoding="utf-8")


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("name", help="Skill folder name (lowercase, dash-separated, e.g. 'odoo19-syntax')")
    parser.add_argument(
        "--description",
        default="Short description of when an assistant should use this skill. Make it specific.",
        help="Description for the SKILL.md frontmatter",
    )
    args = parser.parse_args()

    name = args.name.strip().lower()
    if not name or not name.replace("-", "").replace("_", "").isalnum():
        sys.exit("❌ Skill name must be alphanumeric with optional dashes/underscores")

    target = SKILLS_DIR / name
    if target.exists():
        sys.exit(f"❌ Skill already exists: {target}")

    title = name.replace("-", " ").replace("_", " ").title()
    today = date.today().isoformat()

    write(target / "SKILL.md", SKILL_MD_TEMPLATE.format(name=name, description=args.description, title=title))
    write(target / "README.md", README_TEMPLATE.format(name=name, title=title))
    write(target / "CHANGELOG.md", CHANGELOG_TEMPLATE.format(name=name, today=today))
    write(target / "build.config.json", BUILD_CONFIG_TEMPLATE)
    write(target / "references" / "example.md", EXAMPLE_REFERENCE)
    write(target / "evals" / "example.md", EXAMPLE_EVAL)

    print(f"✅ Created skill at {target}")
    print()
    print("Next steps:")
    print(f"  1. Edit skills/{name}/SKILL.md to flesh out the workflow")
    print(f"  2. Add domain reference files under skills/{name}/references/")
    print(f"  3. Add test prompts under skills/{name}/evals/")
    print(f"  4. Run: python scripts/build.py --skill {name}")


if __name__ == "__main__":
    main()
